INSERT INTO users (name, age) VALUES ("John", 24);
INSERT INTO users (name, age) VALUES ("Maxwell", 32);
INSERT INTO users (name, age) VALUES ("Gabriella", 27);
INSERT INTO users (name, age) VALUES ("Maggie", 20);
INSERT INTO users (name, age) VALUES ("Bobby", 19);
INSERT INTO users (name, age) VALUES ("Marcia", 19);
INSERT INTO users (name, age) VALUES ("Mark", 22);
INSERT INTO users (name, age) VALUES ("Jack", 23);
INSERT INTO users (name, age) VALUES ("Kara", 26);
INSERT INTO users (name, age) VALUES ("Conner", 28);
INSERT INTO users (name, age) VALUES ("Alice", 18);
INSERT INTO users (name, age) VALUES ("Jacob", 35);
INSERT INTO users (name, age) VALUES ("Monica", 25);
INSERT INTO users (name, age) VALUES ("Luis", 21);
INSERT INTO users (name, age) VALUES ("Edith", 35);
INSERT INTO users (name, age) VALUES ("Tyler", 33);
INSERT INTO users (name, age) VALUES ("Viola", 31);
INSERT INTO users (name, age) VALUES ("Ellen", 28);
INSERT INTO users (name, age) VALUES ("Dean", 25);
INSERT INTO users (name, age) VALUES ("Charlotte", 29);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("A new lo-fi song", "music", 50.00, '1/05/2020', "1/15/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Donation for hurricane relief", "charity", 8000.00, '1/20/2020', "2/05/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Funding a new book for being a guide for coding", "books", 500.00, '1/16/2020', "2/01/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Save the Bald Eagles!", "charity", 5000.00, '2/10/2020', "2/29/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Help me fund my new album!", "music", 800.00, '3/05/2020', "3/25/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Help fund this new robot project!", "tech", 2000.00, '1/20/2020', "2/05/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Save the sharks!", "charity", 7000.00, '6/20/2020', "7/05/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("My bed has recently gotten bed bugs!", "charity", 800.00, '1/02/2020', "1/07/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Making the next metalica.", "music", 1000.00, '1/25/2020', "2/05/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Help fund my new video game!", "gaming", 4000.00, '2/01/2020', "3/01/2020");

INSERT INTO pledges (user_id, project_id, amount) VALUES (3, 9, 161);
INSERT INTO pledges (user_id, project_id, amount) VALUES (16, 5, 72);
INSERT INTO pledges (user_id, project_id, amount) VALUES (12, 1, 174);
INSERT INTO pledges (user_id, project_id, amount) VALUES (2, 9, 86);
INSERT INTO pledges (user_id, project_id, amount) VALUES (13, 3, 32);
INSERT INTO pledges (user_id, project_id, amount) VALUES (11, 5, 95);
INSERT INTO pledges (user_id, project_id, amount) VALUES (16, 4, 180);
INSERT INTO pledges (user_id, project_id, amount) VALUES (16, 5, 190);
INSERT INTO pledges (user_id, project_id, amount) VALUES (15, 1, 97);
INSERT INTO pledges (user_id, project_id, amount) VALUES (3, 9, 58);
INSERT INTO pledges (user_id, project_id, amount) VALUES (5, 9, 28);
INSERT INTO pledges (user_id, project_id, amount) VALUES (13, 5, 188);
INSERT INTO pledges (user_id, project_id, amount) VALUES (14, 1, 83);
INSERT INTO pledges (user_id, project_id, amount) VALUES (1, 4, 172);
INSERT INTO pledges (user_id, project_id, amount) VALUES (16, 10, 56);
INSERT INTO pledges (user_id, project_id, amount) VALUES (12, 2, 86);
INSERT INTO pledges (user_id, project_id, amount) VALUES (18, 7, 120);
INSERT INTO pledges (user_id, project_id, amount) VALUES (2, 1, 200);
INSERT INTO pledges (user_id, project_id, amount) VALUES (11, 9, 170);
INSERT INTO pledges (user_id, project_id, amount) VALUES (2, 2, 13);
INSERT INTO pledges (user_id, project_id, amount) VALUES (10, 3, 183);
INSERT INTO pledges (user_id, project_id, amount) VALUES (18, 1, 29);
INSERT INTO pledges (user_id, project_id, amount) VALUES (7, 5, 52);
INSERT INTO pledges (user_id, project_id, amount) VALUES (11, 6, 198);
INSERT INTO pledges (user_id, project_id, amount) VALUES (17, 7, 183);
INSERT INTO pledges (user_id, project_id, amount) VALUES (20, 5, 167);
INSERT INTO pledges (user_id, project_id, amount) VALUES (13, 10, 58);
INSERT INTO pledges (user_id, project_id, amount) VALUES (14, 2, 99);
INSERT INTO pledges (user_id, project_id, amount) VALUES (12, 8, 122);
INSERT INTO pledges (user_id, project_id, amount) VALUES (12, 1, 85);