INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);
INSERT INTO users (name, age) VALUES ("Bob", 21);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ( "Hot-pot camel back", "kitchen utensil", 230, 02202020, 03012020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ( "Hot-pot camel back", "kitchen utensil", 230, 02202020, 03012020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ( "Hot-pot camel back", "kitchen utensil", 230, 02202020, 03012020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ( "Hot-pot camel back", "kitchen utensil", 230, 02202020, 03012020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ( "Hot-pot camel back", "kitchen utensil", 230, 02202020, 03012020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ( "Hot-pot camel back", "kitchen utensil", 230, 02202020, 03012020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ( "Hot-pot camel back", "kitchen utensil", 230, 02202020, 03012020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ( "Hot-pot camel back", "kitchen utensil", 230, 02202020, 03012020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ( "Hot-pot camel back", "kitchen utensil", 230, 02202020, 03012020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ( "Hot-pot camel back", "kitchen utensil", 230, 02202020, 03012020);

INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 2, 3);